### ISSUE TITLE
Pre-existing Zenodo release not recognized

### ISSUE THREAD

**Issue by Aariq** [fairdataihub/codefair-app#112]
I installed the app into a repo that already had a GitHub release archived with Zenodo and the app failed the FAIR software release check (https://github.com/cct-datascience/github-actions-for-research/issues/3).  I'm not familiar with how the app checks for a Zenodo release, so I'm not sure if this is something it could detect if it was already done not with the app.

**Comment by slugb0t** [comment]
Sorry for the confusion on that, Codefair currently requires that Zenodo releases be made through the app to pass the FAIR software release check. This means that any Zenodo releases created prior to installing Codefair will not be automatically detected as valid for this specific check.

We appreciate your input, as it let's us know where we can explore improvements to better accommodate new users. Please feel free to share any further thoughts or suggestions!

**Comment by slugb0t** [comment]
@Aariq We've updated our documentation to specify a bit more on the details of when a fair check passes [here](https://docs.codefair.io/docs/dashboard.html)

**Comment by kelly-sovacool** [comment]
It would be nice to be able to cure the failing check by manually providing a zenodo link or DOI through the dashboard.

<img width="1052" height="263" alt="Image" src="https://github.com/user-attachments/assets/9dd976fe-729a-4175-825e-275726b481c9" />

Even better yet, it would be great if codefair could detect the presence of a zenodo DOI in an existing citation.cff file.

**Comment by slugb0t** [comment]
@kelly-sovacool we've created an update with our latest version to detect existing DOI's in citation.cff and codemeta.json files! We appreciate the idea as it was the source of inspiration for this feature!
